version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - 5460:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: rasp_db
    networks:
      - school-rasp

  php-fpm:
    container_name: php-fpm
    build:
      context: ./build/php-fpm
      dockerfile: Dockerfile
      args:
        - XDEBUG_MODE
        - XDEBUG_CLIENT_HOST
    environment:
      - SYMFONY_ENV
      - PHP_IDE_CONFIG
    ports:
      - 9612:9000
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
      - ./school-rasp/:/var/www/school-rasp/:delegated
    depends_on:
      - postgres
    networks:
      - school-rasp

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8560:80
    depends_on:
      - php-fpm
    networks:
      - school-rasp
    volumes:
      - ./build/nginx/local:/etc/nginx/conf.d/
      - ./build/nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf
      - ./school-rasp/public:/var/www/school-rasp/public:rw,cached

networks:
  school-rasp:
